/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    posts: Post;
    'og-img': OgImg;
    documents: Document;
    users: User;
  };
  globals: {
    'privacy-policy': PrivacyPolicy;
    'cookie-policy': CookiePolicy;
  };
}
export interface Post {
  id: string;
  title: string;
  slug?: string;
  editSlug?: boolean;
  excerpt?: string;
  content?: {
    [k: string]: unknown;
  }[];
  displayDate?: string;
  author?: string | User;
  meta?: {
    title?: string;
    description?: string;
    image?: string | OgImg;
  };
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface OgImg {
  id: string;
  title?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Document {
  id: string;
  title?: string;
  publicTitle?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface PrivacyPolicy {
  id: string;
  content?: {
    [k: string]: unknown;
  }[];
  displayDate?: string;
  updatedAt?: string;
  createdAt?: string;
}
export interface CookiePolicy {
  id: string;
  content?: {
    [k: string]: unknown;
  }[];
  displayDate?: string;
  updatedAt?: string;
  createdAt?: string;
}
